CREATE TABLE devices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID        NOT NULL,
    request_id UUID        NOT NULL,
    platform   VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_devices_public_id UNIQUE (public_id),
    CONSTRAINT uk_devices_request_id UNIQUE (request_id)
);

CREATE TABLE device_refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  BIGINT      NOT NULL,
    session_id UUID        NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_device_refresh_tokens_device
        FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT uk_device_refresh_tokens_session_id UNIQUE (session_id)
);

CREATE INDEX idx_device_refresh_tokens_device_id
    ON device_refresh_tokens (device_id);
