CREATE TABLE sigh_likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigh_id    BIGINT      NOT NULL,
    device_id  BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_sigh_likes_sigh FOREIGN KEY (sigh_id) REFERENCES sighs (id),
    CONSTRAINT fk_sigh_likes_device FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT uk_sigh_likes_sigh_device UNIQUE (sigh_id, device_id)
);

ALTER TABLE sighs
    ADD COLUMN like_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
