CREATE TABLE device_challenges
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge   VARCHAR(43) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_device_challenges_challenge UNIQUE (challenge)
);

CREATE INDEX idx_device_challenges_expires_at
    ON device_challenges (expires_at);
