-- KST 날짜와 플랫폼별 최종 집계다. 기기별 활동 원본의 보관 기간과 독립적으로 유지한다.
CREATE TABLE device_activity_summaries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_date DATE        NOT NULL,
    platform      VARCHAR(20) NOT NULL,
    dau           BIGINT      NOT NULL,
    mau           BIGINT      NOT NULL,
    aggregated_at TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_device_activity_summaries_date_platform
        UNIQUE (activity_date, platform),
    CONSTRAINT ck_device_activity_summaries_counts
        CHECK (dau >= 0 AND mau >= dau)
);
