-- 구버전 서버의 쓰기를 중단한 뒤 기존 한숨과 연결 기록을 제거한다.

CREATE TABLE emotions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID                  NOT NULL,
    location   geometry(Point, 4326) NOT NULL,
    memo       VARCHAR(50),
    nickname   VARCHAR(50)           NOT NULL,
    deleted_at TIMESTAMPTZ,
    device_id  BIGINT,
    like_count BIGINT                NOT NULL DEFAULT 0,
    version    BIGINT                NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ           NOT NULL,
    updated_at TIMESTAMPTZ           NOT NULL,
    CONSTRAINT uk_emotions_request_id UNIQUE (request_id),
    CONSTRAINT fk_emotions_device FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE INDEX idx_emotions_location_gist ON emotions USING GIST (location);

TRUNCATE TABLE sigh_likes, sigh_reports, sigh_blocks, device_blocks RESTART IDENTITY;

ALTER TABLE sigh_likes DROP CONSTRAINT fk_sigh_likes_sigh;
ALTER TABLE sigh_reports DROP CONSTRAINT fk_sigh_reports_sigh;
ALTER TABLE sigh_blocks DROP CONSTRAINT fk_sigh_blocks_sigh;
ALTER TABLE device_blocks DROP CONSTRAINT fk_device_blocks_origin_sigh;

DROP TABLE sighs;

ALTER TABLE sigh_likes RENAME TO emotion_likes;
ALTER TABLE sigh_reports RENAME TO emotion_reports;
ALTER TABLE sigh_blocks RENAME TO emotion_blocks;

ALTER TABLE emotion_likes RENAME COLUMN sigh_id TO emotion_id;
ALTER TABLE emotion_reports RENAME COLUMN sigh_id TO emotion_id;
ALTER TABLE emotion_blocks RENAME COLUMN sigh_id TO emotion_id;
ALTER TABLE device_blocks RENAME COLUMN origin_sigh_id TO origin_emotion_id;

ALTER TABLE emotion_likes RENAME CONSTRAINT sigh_likes_pkey TO emotion_likes_pkey;
ALTER TABLE emotion_likes ADD CONSTRAINT fk_emotion_likes_emotion
    FOREIGN KEY (emotion_id) REFERENCES emotions (id);
ALTER TABLE emotion_likes RENAME CONSTRAINT fk_sigh_likes_device TO fk_emotion_likes_device;
ALTER TABLE emotion_likes RENAME CONSTRAINT uk_sigh_likes_sigh_device TO uk_emotion_likes_emotion_device;

ALTER TABLE emotion_reports RENAME CONSTRAINT sigh_reports_pkey TO emotion_reports_pkey;
ALTER TABLE emotion_reports ADD CONSTRAINT fk_emotion_reports_emotion
    FOREIGN KEY (emotion_id) REFERENCES emotions (id);
ALTER TABLE emotion_reports RENAME CONSTRAINT fk_sigh_reports_device TO fk_emotion_reports_device;
ALTER TABLE emotion_reports RENAME CONSTRAINT uk_sigh_reports_sigh_reporter TO uk_emotion_reports_emotion_reporter;

ALTER TABLE emotion_blocks RENAME CONSTRAINT sigh_blocks_pkey TO emotion_blocks_pkey;
ALTER TABLE emotion_blocks RENAME CONSTRAINT fk_sigh_blocks_device TO fk_emotion_blocks_device;
ALTER TABLE emotion_blocks ADD CONSTRAINT fk_emotion_blocks_emotion
    FOREIGN KEY (emotion_id) REFERENCES emotions (id);
ALTER TABLE emotion_blocks RENAME CONSTRAINT uk_sigh_blocks_blocker_sigh TO uk_emotion_blocks_blocker_emotion;
ALTER TABLE device_blocks ADD CONSTRAINT fk_device_blocks_origin_emotion
    FOREIGN KEY (origin_emotion_id) REFERENCES emotions (id);

ALTER SEQUENCE sigh_likes_id_seq RENAME TO emotion_likes_id_seq;
ALTER SEQUENCE sigh_reports_id_seq RENAME TO emotion_reports_id_seq;
ALTER SEQUENCE sigh_blocks_id_seq RENAME TO emotion_blocks_id_seq;
