-- activity_date는 활동 시각을 Asia/Seoul 기준으로 변환한 날짜다.
CREATE TABLE device_daily_activities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id     BIGINT      NOT NULL,
    activity_date DATE        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_device_daily_activities_device
        FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT uk_device_daily_activities_date_device
        UNIQUE (activity_date, device_id)
);
