CREATE TABLE groups
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   UUID         NOT NULL,
    name        VARCHAR(10)  NOT NULL,
    description VARCHAR(100),
    invite_code VARCHAR(6)   NOT NULL,
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_groups_public_id
        UNIQUE (public_id),
    CONSTRAINT uk_groups_invite_code
        UNIQUE (invite_code)
);

CREATE UNIQUE INDEX uk_groups_name_active
    ON groups (name) WHERE deleted_at IS NULL;

CREATE TABLE group_stamps
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id         BIGINT      NOT NULL,
    text             VARCHAR(4)  NOT NULL,
    text_color       VARCHAR(9)  NOT NULL,
    background_color VARCHAR(9)  NOT NULL,
    frame            VARCHAR(20) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_group_stamps_group_id
        UNIQUE (group_id),
    CONSTRAINT fk_group_stamps_group
        FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE group_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID        NOT NULL,
    group_id   BIGINT      NOT NULL,
    device_id  BIGINT      NOT NULL,
    role       VARCHAR(20) NOT NULL,
    left_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_group_members_public_id
        UNIQUE (public_id),
    CONSTRAINT fk_group_members_group
        FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_members_device
        FOREIGN KEY (device_id) REFERENCES devices (id)
);

CREATE UNIQUE INDEX uk_group_members_active
    ON group_members (group_id, device_id) WHERE left_at IS NULL;

CREATE UNIQUE INDEX uk_group_members_owner
    ON group_members (group_id) WHERE role = 'OWNER' AND left_at IS NULL;

CREATE INDEX idx_group_members_device
    ON group_members (device_id) WHERE left_at IS NULL;
