CREATE TABLE emotion_emojis
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emotion_id BIGINT      NOT NULL,
    device_id  BIGINT      NOT NULL,
    emoji_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_emotion_emojis_emotion FOREIGN KEY (emotion_id) REFERENCES emotions (id),
    CONSTRAINT fk_emotion_emojis_device FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT uk_emotion_emojis_emotion_device_type UNIQUE (emotion_id, device_id, emoji_type)
);
