CREATE TABLE sigh_blocks
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_device_id BIGINT      NOT NULL,
    sigh_id           BIGINT      NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_sigh_blocks_device
        FOREIGN KEY (blocker_device_id) REFERENCES devices (id),
    CONSTRAINT fk_sigh_blocks_sigh
        FOREIGN KEY (sigh_id) REFERENCES sighs (id),
    CONSTRAINT uk_sigh_blocks_blocker_sigh
        UNIQUE (blocker_device_id, sigh_id)
);

CREATE TABLE device_blocks
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_device_id BIGINT      NOT NULL,
    blocked_device_id BIGINT      NOT NULL,
    origin_sigh_id    BIGINT      NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_device_blocks_blocker
        FOREIGN KEY (blocker_device_id) REFERENCES devices (id),
    CONSTRAINT fk_device_blocks_blocked
        FOREIGN KEY (blocked_device_id) REFERENCES devices (id),
    CONSTRAINT fk_device_blocks_origin_sigh
        FOREIGN KEY (origin_sigh_id) REFERENCES sighs (id),
    CONSTRAINT uk_device_blocks_blocker_blocked
        UNIQUE (blocker_device_id, blocked_device_id),
    CONSTRAINT ck_device_blocks_not_self
        CHECK (blocker_device_id <> blocked_device_id)
);
