CREATE TABLE app_version
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform              VARCHAR(20)  NOT NULL,
    min_supported_version VARCHAR(32)  NOT NULL,
    latest_version        VARCHAR(32)  NOT NULL,
    store_url             VARCHAR(500) NOT NULL,
    is_active             BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_app_version_platform
        UNIQUE (platform),
    CONSTRAINT ck_app_version_platform
        CHECK (platform IN ('ANDROID', 'IOS')),
    CONSTRAINT ck_app_version_versions
        CHECK (
            CASE
                WHEN min_supported_version ~ '^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)$'
                    AND latest_version ~ '^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)$'
                THEN string_to_array(min_supported_version, '.')::NUMERIC[]
                    <= string_to_array(latest_version, '.')::NUMERIC[]
                ELSE FALSE
            END
        ),
    CONSTRAINT ck_app_version_store_url_not_blank
        CHECK (btrim(store_url) <> '')
);
