CREATE TABLE group_daily_presses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT      NOT NULL,
    press_date  DATE        NOT NULL,
    state       VARCHAR(20) NOT NULL,
    press_count BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_group_daily_presses_group_date_state
        UNIQUE (group_id, press_date, state),
    CONSTRAINT ck_group_daily_presses_count
        CHECK (press_count > 0),
    CONSTRAINT fk_group_daily_presses_group
        FOREIGN KEY (group_id) REFERENCES groups (id)
);
