-- 무결성 증명 복호화를 위한 구글 호출의 프로젝트 단위 일일 예산.
-- IP 당 제한으로는 분산 요청이 구글 일일 할당량을 소진시킬 수 있어 전역 상한을 둔다.
CREATE TABLE device_attestation_budgets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_date DATE        NOT NULL,
    call_count  INTEGER     NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_device_attestation_budgets_budget_date UNIQUE (budget_date)
);
