CREATE TABLE audio_uploads
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id          VARCHAR(36) NOT NULL,
    device_id          BIGINT      NOT NULL,
    object_key         TEXT        NOT NULL,
    content_type       TEXT        NOT NULL,
    content_length     BIGINT      NOT NULL,
    expires_at         TIMESTAMPTZ NOT NULL,
    claimed_request_id UUID,
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_audio_uploads_upload_id UNIQUE (upload_id),
    CONSTRAINT uk_audio_uploads_object_key UNIQUE (object_key),
    CONSTRAINT fk_audio_uploads_device FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT ck_audio_uploads_content_length CHECK (content_length > 0)
);
