CREATE TABLE device_region_daily_presses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    press_date  DATE        NOT NULL,
    region_code VARCHAR(8)  NOT NULL,
    state       VARCHAR(20) NOT NULL,
    device_id   BIGINT      NOT NULL,
    press_count BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_device_region_daily_presses_date_region_state_device
        UNIQUE (press_date, region_code, state, device_id),
    CONSTRAINT ck_device_region_daily_presses_count
        CHECK (press_count > 0),
    CONSTRAINT ck_device_region_daily_presses_region_code
        CHECK (region_code ~ '^[0-9]{8}$'),
    CONSTRAINT fk_device_region_daily_presses_region
        FOREIGN KEY (region_code) REFERENCES regions (code),
    CONSTRAINT fk_device_region_daily_presses_device
        FOREIGN KEY (device_id) REFERENCES devices (id)
);
