-- 개인 감정 프레스에서 지역을 뺀다(#689). 개발 서버의 시험 데이터는 이전하지 않는다.
-- V20261006_1 는 dev, develop 에 적용됐으므로 수정하지 않고 새 버전으로 바꿔 끼운다.

DROP TABLE device_region_daily_presses;

CREATE TABLE device_daily_presses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    press_date  DATE        NOT NULL,
    state       VARCHAR(20) NOT NULL,
    device_id   BIGINT      NOT NULL,
    press_count BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_device_daily_presses_date_state_device
        UNIQUE (press_date, state, device_id),
    CONSTRAINT ck_device_daily_presses_count
        CHECK (press_count > 0),
    CONSTRAINT fk_device_daily_presses_device
        FOREIGN KEY (device_id) REFERENCES devices (id)
);
