package com.pheeeew.device.infra.attestation;

public enum PlayIntegrityRejection {

    ATTESTATION_REQUIRED,
    UNSUPPORTED_PLATFORM,
    CREDENTIALS_MISSING,
    MALFORMED_TOKEN,
    CHALLENGE_MISSING,
    CHALLENGE_UNUSABLE,
    GOOGLE_QUOTA_EXHAUSTED,
    GOOGLE_UNAVAILABLE,
    MALFORMED_PAYLOAD,
    PACKAGE_MISMATCH,
    APP_UNRECOGNIZED,
    DEVICE_INTEGRITY_MISSING,
    CHALLENGE_MISMATCH,
    CHALLENGE_INVALID
}
