package com.pheeeew.device.infra.attestation.appattest;

public enum AppAttestRejection {

    ATTESTATION_REQUIRED,
    PROPERTIES_MISSING,
    MALFORMED_TOKEN,
    KEY_ID_MISSING,
    MALFORMED_ATTESTATION,
    UNSUPPORTED_FORMAT,
    MALFORMED_AUTH_DATA,
    CHALLENGE_INVALID,
    CERTIFICATE_CHAIN_INVALID,
    NONCE_MISMATCH,
    KEY_ID_MISMATCH,
    APP_ID_MISMATCH,
    COUNTER_NOT_ZERO,
    ENVIRONMENT_MISMATCH,
    CREDENTIAL_ID_MISMATCH
}
