spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  forward-headers-strategy: native

logging:
  level:
    com.pheeeew: DEBUG
    org.hibernate.SQL: DEBUG
