spring:
  application:
    name: pheeeew
  profiles:
    default: local
  config:
    import: classpath:application-log.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  sql:
    init:
      mode: never

pheeeew:
  jwt:
    private-key-base64: ${JWT_PRIVATE_KEY_BASE64}
    public-key-base64: ${JWT_PUBLIC_KEY_BASE64}
  token:
    access-ttl: PT30M
    registration-retry-window: PT5M

management:
  prometheus:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
